name = "tokenmaniac/base64"
version = "0.1.1"
repository = "https://github.com/TokenManiac/Base64"
description = "The fastest base64 in pure luau yet!"
authors = ["GPT-5-Thinking"]
license = "UNLICENSE"

includes = [
    "pesde.toml",
    "README.md",
    "LICENSE",
    "lib/**",
    "docs/**/*.md",
]

[target]
environment = "luau"
lib = "src.luau"

[indices]
default = "https://github.com/pesde-pkg/index"